# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4 smartindent

language: python
jobs:
  include:
  - name: python2.7
    python: "2.7"
    env: PYVERSIONS=python2.7
script: PYVERSIONS=$PYVERSIONS make testinstallvirtualenv
